// Code generated by ent, DO NOT EDIT.

package todofilterhistory

import (
	"time"
	"todo-app/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldUserID, v))
}

// Query applies equality check predicate on the "query" field. It's identical to QueryEQ.
func Query(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldQuery, v))
}

// FunctionName applies equality check predicate on the "function_name" field. It's identical to FunctionNameEQ.
func FunctionName(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldFunctionName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotIn(FieldUserID, vs...))
}

// QueryEQ applies the EQ predicate on the "query" field.
func QueryEQ(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldQuery, v))
}

// QueryNEQ applies the NEQ predicate on the "query" field.
func QueryNEQ(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNEQ(FieldQuery, v))
}

// QueryIn applies the In predicate on the "query" field.
func QueryIn(vs ...string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIn(FieldQuery, vs...))
}

// QueryNotIn applies the NotIn predicate on the "query" field.
func QueryNotIn(vs ...string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotIn(FieldQuery, vs...))
}

// QueryGT applies the GT predicate on the "query" field.
func QueryGT(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGT(FieldQuery, v))
}

// QueryGTE applies the GTE predicate on the "query" field.
func QueryGTE(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGTE(FieldQuery, v))
}

// QueryLT applies the LT predicate on the "query" field.
func QueryLT(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLT(FieldQuery, v))
}

// QueryLTE applies the LTE predicate on the "query" field.
func QueryLTE(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLTE(FieldQuery, v))
}

// QueryContains applies the Contains predicate on the "query" field.
func QueryContains(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldContains(FieldQuery, v))
}

// QueryHasPrefix applies the HasPrefix predicate on the "query" field.
func QueryHasPrefix(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldHasPrefix(FieldQuery, v))
}

// QueryHasSuffix applies the HasSuffix predicate on the "query" field.
func QueryHasSuffix(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldHasSuffix(FieldQuery, v))
}

// QueryEqualFold applies the EqualFold predicate on the "query" field.
func QueryEqualFold(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEqualFold(FieldQuery, v))
}

// QueryContainsFold applies the ContainsFold predicate on the "query" field.
func QueryContainsFold(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldContainsFold(FieldQuery, v))
}

// FunctionNameEQ applies the EQ predicate on the "function_name" field.
func FunctionNameEQ(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldFunctionName, v))
}

// FunctionNameNEQ applies the NEQ predicate on the "function_name" field.
func FunctionNameNEQ(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNEQ(FieldFunctionName, v))
}

// FunctionNameIn applies the In predicate on the "function_name" field.
func FunctionNameIn(vs ...string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIn(FieldFunctionName, vs...))
}

// FunctionNameNotIn applies the NotIn predicate on the "function_name" field.
func FunctionNameNotIn(vs ...string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotIn(FieldFunctionName, vs...))
}

// FunctionNameGT applies the GT predicate on the "function_name" field.
func FunctionNameGT(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGT(FieldFunctionName, v))
}

// FunctionNameGTE applies the GTE predicate on the "function_name" field.
func FunctionNameGTE(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGTE(FieldFunctionName, v))
}

// FunctionNameLT applies the LT predicate on the "function_name" field.
func FunctionNameLT(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLT(FieldFunctionName, v))
}

// FunctionNameLTE applies the LTE predicate on the "function_name" field.
func FunctionNameLTE(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLTE(FieldFunctionName, v))
}

// FunctionNameContains applies the Contains predicate on the "function_name" field.
func FunctionNameContains(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldContains(FieldFunctionName, v))
}

// FunctionNameHasPrefix applies the HasPrefix predicate on the "function_name" field.
func FunctionNameHasPrefix(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldHasPrefix(FieldFunctionName, v))
}

// FunctionNameHasSuffix applies the HasSuffix predicate on the "function_name" field.
func FunctionNameHasSuffix(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldHasSuffix(FieldFunctionName, v))
}

// FunctionNameIsNil applies the IsNil predicate on the "function_name" field.
func FunctionNameIsNil() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIsNull(FieldFunctionName))
}

// FunctionNameNotNil applies the NotNil predicate on the "function_name" field.
func FunctionNameNotNil() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotNull(FieldFunctionName))
}

// FunctionNameEqualFold applies the EqualFold predicate on the "function_name" field.
func FunctionNameEqualFold(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEqualFold(FieldFunctionName, v))
}

// FunctionNameContainsFold applies the ContainsFold predicate on the "function_name" field.
func FunctionNameContainsFold(v string) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldContainsFold(FieldFunctionName, v))
}

// ArgsIsNil applies the IsNil predicate on the "args" field.
func ArgsIsNil() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIsNull(FieldArgs))
}

// ArgsNotNil applies the NotNil predicate on the "args" field.
func ArgsNotNil() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotNull(FieldArgs))
}

// ResultTodoIdsIsNil applies the IsNil predicate on the "result_todo_ids" field.
func ResultTodoIdsIsNil() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIsNull(FieldResultTodoIds))
}

// ResultTodoIdsNotNil applies the NotNil predicate on the "result_todo_ids" field.
func ResultTodoIdsNotNil() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotNull(FieldResultTodoIds))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TodoFilterHistory) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TodoFilterHistory) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TodoFilterHistory) predicate.TodoFilterHistory {
	return predicate.TodoFilterHistory(sql.NotPredicates(p))
}
