// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v5"
	"todo-app/handlers"
	"todo-app/middlewares"
	"todo-app/providers"
	"todo-app/routes"
	"todo-app/services"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	echoEcho := echo.New()
	client, cleanup, err := providers.NewEntClient()
	if err != nil {
		return nil, nil, err
	}
	todoService := services.NewTodoService(client)
	todoHandler := handlers.NewTodoHandler(todoService)
	middlewareFunc := middlewares.NewTransactionMiddleware(client)
	router := routes.NewRouter(todoHandler, client, middlewareFunc)
	app := NewApp(echoEcho, router)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Engine *echo.Echo
	Router *routes.Router
}

func NewApp(e *echo.Echo, r *routes.Router) *App {
	return &App{Engine: e, Router: r}
}
