// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v5"
	"todo-app/handlers"
	"todo-app/middlewares"
	"todo-app/providers"
	"todo-app/routes"
	"todo-app/services"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	echoEcho := echo.New()
	client, cleanup, err := providers.NewEntClient()
	if err != nil {
		return nil, nil, err
	}
	middlewareFunc := middlewares.NewTransactionMiddleware(client)
	todoService := services.NewTodoService()
	todoHandler := handlers.NewTodoHandler(todoService)
	todoRouter := routes.NewTodoRouter(todoHandler, middlewareFunc)
	router := routes.NewRouter(middlewareFunc, todoRouter)
	app := NewApp(echoEcho, router)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// provider
var providerSet = wire.NewSet(providers.NewEntClient)

// middleware
var middlewareSet = wire.NewSet(middlewares.NewTransactionMiddleware)

// handler
var handlerSet = wire.NewSet(handlers.NewTodoHandler)

// service
var serviceSet = wire.NewSet(services.NewTodoService)

// route
var routeSet = wire.NewSet(routes.NewRouter, routes.NewTodoRouter)

// app
var appSet = wire.NewSet(echo.New, NewApp)

type App struct {
	Engine *echo.Echo
	Router *routes.Router
}

func NewApp(e *echo.Echo, r *routes.Router) *App {
	return &App{Engine: e, Router: r}
}
