// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"todo-app/ent/schema"
	"todo-app/ent/todo"
	"todo-app/ent/todofilterhistory"
	"todo-app/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTitle is the schema descriptor for title field.
	todoDescTitle := todoFields[1].Descriptor()
	// todo.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todo.TitleValidator = func() func(string) error {
		validators := todoDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// todoDescDescription is the schema descriptor for description field.
	todoDescDescription := todoFields[2].Descriptor()
	// todo.DefaultDescription holds the default value on creation for the description field.
	todo.DefaultDescription = todoDescDescription.Default.(string)
	// todo.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	todo.DescriptionValidator = func() func(string) error {
		validators := todoDescDescription.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(description string) error {
			for _, fn := range fns {
				if err := fn(description); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[4].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
	// todoDescUpdatedAt is the schema descriptor for updated_at field.
	todoDescUpdatedAt := todoFields[5].Descriptor()
	// todo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todo.DefaultUpdatedAt = todoDescUpdatedAt.Default.(func() time.Time)
	// todo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todo.UpdateDefaultUpdatedAt = todoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// todoDescID is the schema descriptor for id field.
	todoDescID := todoFields[0].Descriptor()
	// todo.IDValidator is a validator for the "id" field. It is called by the builders before save.
	todo.IDValidator = todoDescID.Validators[0].(func(int) error)
	todofilterhistoryFields := schema.TodoFilterHistory{}.Fields()
	_ = todofilterhistoryFields
	// todofilterhistoryDescQuery is the schema descriptor for query field.
	todofilterhistoryDescQuery := todofilterhistoryFields[2].Descriptor()
	// todofilterhistory.QueryValidator is a validator for the "query" field. It is called by the builders before save.
	todofilterhistory.QueryValidator = todofilterhistoryDescQuery.Validators[0].(func(string) error)
	// todofilterhistoryDescFunctionName is the schema descriptor for function_name field.
	todofilterhistoryDescFunctionName := todofilterhistoryFields[3].Descriptor()
	// todofilterhistory.FunctionNameValidator is a validator for the "function_name" field. It is called by the builders before save.
	todofilterhistory.FunctionNameValidator = todofilterhistoryDescFunctionName.Validators[0].(func(string) error)
	// todofilterhistoryDescCreatedAt is the schema descriptor for created_at field.
	todofilterhistoryDescCreatedAt := todofilterhistoryFields[6].Descriptor()
	// todofilterhistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	todofilterhistory.DefaultCreatedAt = todofilterhistoryDescCreatedAt.Default.(func() time.Time)
	// todofilterhistoryDescID is the schema descriptor for id field.
	todofilterhistoryDescID := todofilterhistoryFields[0].Descriptor()
	// todofilterhistory.DefaultID holds the default value on creation for the id field.
	todofilterhistory.DefaultID = todofilterhistoryDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
