// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"todo-app/ent/todofilterhistory"
	"todo-app/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// TodoFilterHistory is the model entity for the TodoFilterHistory schema.
type TodoFilterHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Query holds the value of the "query" field.
	Query string `json:"query,omitempty"`
	// FunctionName holds the value of the "function_name" field.
	FunctionName string `json:"function_name,omitempty"`
	// Args holds the value of the "args" field.
	Args map[string]interface{} `json:"args,omitempty"`
	// ResultTodoIds holds the value of the "result_todo_ids" field.
	ResultTodoIds []int `json:"result_todo_ids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TodoFilterHistoryQuery when eager-loading is set.
	Edges        TodoFilterHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TodoFilterHistoryEdges holds the relations/edges for other nodes in the graph.
type TodoFilterHistoryEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TodoFilterHistoryEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TodoFilterHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case todofilterhistory.FieldArgs, todofilterhistory.FieldResultTodoIds:
			values[i] = new([]byte)
		case todofilterhistory.FieldUserID:
			values[i] = new(sql.NullInt64)
		case todofilterhistory.FieldQuery, todofilterhistory.FieldFunctionName:
			values[i] = new(sql.NullString)
		case todofilterhistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case todofilterhistory.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TodoFilterHistory fields.
func (_m *TodoFilterHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case todofilterhistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case todofilterhistory.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case todofilterhistory.FieldQuery:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field query", values[i])
			} else if value.Valid {
				_m.Query = value.String
			}
		case todofilterhistory.FieldFunctionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field function_name", values[i])
			} else if value.Valid {
				_m.FunctionName = value.String
			}
		case todofilterhistory.FieldArgs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field args", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Args); err != nil {
					return fmt.Errorf("unmarshal field args: %w", err)
				}
			}
		case todofilterhistory.FieldResultTodoIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_todo_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultTodoIds); err != nil {
					return fmt.Errorf("unmarshal field result_todo_ids: %w", err)
				}
			}
		case todofilterhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TodoFilterHistory.
// This includes values selected through modifiers, order, etc.
func (_m *TodoFilterHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TodoFilterHistory entity.
func (_m *TodoFilterHistory) QueryUser() *UserQuery {
	return NewTodoFilterHistoryClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TodoFilterHistory.
// Note that you need to call TodoFilterHistory.Unwrap() before calling this method if this TodoFilterHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TodoFilterHistory) Update() *TodoFilterHistoryUpdateOne {
	return NewTodoFilterHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TodoFilterHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TodoFilterHistory) Unwrap() *TodoFilterHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TodoFilterHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TodoFilterHistory) String() string {
	var builder strings.Builder
	builder.WriteString("TodoFilterHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("query=")
	builder.WriteString(_m.Query)
	builder.WriteString(", ")
	builder.WriteString("function_name=")
	builder.WriteString(_m.FunctionName)
	builder.WriteString(", ")
	builder.WriteString("args=")
	builder.WriteString(fmt.Sprintf("%v", _m.Args))
	builder.WriteString(", ")
	builder.WriteString("result_todo_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultTodoIds))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TodoFilterHistories is a parsable slice of TodoFilterHistory.
type TodoFilterHistories []*TodoFilterHistory
