// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"todo-app/ent/predicate"
	"todo-app/ent/todofilterhistory"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TodoFilterHistoryDelete is the builder for deleting a TodoFilterHistory entity.
type TodoFilterHistoryDelete struct {
	config
	hooks    []Hook
	mutation *TodoFilterHistoryMutation
}

// Where appends a list predicates to the TodoFilterHistoryDelete builder.
func (_d *TodoFilterHistoryDelete) Where(ps ...predicate.TodoFilterHistory) *TodoFilterHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TodoFilterHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoFilterHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TodoFilterHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(todofilterhistory.Table, sqlgraph.NewFieldSpec(todofilterhistory.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TodoFilterHistoryDeleteOne is the builder for deleting a single TodoFilterHistory entity.
type TodoFilterHistoryDeleteOne struct {
	_d *TodoFilterHistoryDelete
}

// Where appends a list predicates to the TodoFilterHistoryDelete builder.
func (_d *TodoFilterHistoryDeleteOne) Where(ps ...predicate.TodoFilterHistory) *TodoFilterHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TodoFilterHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{todofilterhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TodoFilterHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
