// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"todo-app/ent/todofilterhistory"
	"todo-app/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TodoFilterHistoryCreate is the builder for creating a TodoFilterHistory entity.
type TodoFilterHistoryCreate struct {
	config
	mutation *TodoFilterHistoryMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TodoFilterHistoryCreate) SetUserID(v int) *TodoFilterHistoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetQuery sets the "query" field.
func (_c *TodoFilterHistoryCreate) SetQuery(v string) *TodoFilterHistoryCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetFunctionName sets the "function_name" field.
func (_c *TodoFilterHistoryCreate) SetFunctionName(v string) *TodoFilterHistoryCreate {
	_c.mutation.SetFunctionName(v)
	return _c
}

// SetNillableFunctionName sets the "function_name" field if the given value is not nil.
func (_c *TodoFilterHistoryCreate) SetNillableFunctionName(v *string) *TodoFilterHistoryCreate {
	if v != nil {
		_c.SetFunctionName(*v)
	}
	return _c
}

// SetArgs sets the "args" field.
func (_c *TodoFilterHistoryCreate) SetArgs(v map[string]interface{}) *TodoFilterHistoryCreate {
	_c.mutation.SetArgs(v)
	return _c
}

// SetResultTodoIds sets the "result_todo_ids" field.
func (_c *TodoFilterHistoryCreate) SetResultTodoIds(v []int) *TodoFilterHistoryCreate {
	_c.mutation.SetResultTodoIds(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TodoFilterHistoryCreate) SetCreatedAt(v time.Time) *TodoFilterHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TodoFilterHistoryCreate) SetNillableCreatedAt(v *time.Time) *TodoFilterHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TodoFilterHistoryCreate) SetID(v uuid.UUID) *TodoFilterHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TodoFilterHistoryCreate) SetNillableID(v *uuid.UUID) *TodoFilterHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TodoFilterHistoryCreate) SetUser(v *User) *TodoFilterHistoryCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TodoFilterHistoryMutation object of the builder.
func (_c *TodoFilterHistoryCreate) Mutation() *TodoFilterHistoryMutation {
	return _c.mutation
}

// Save creates the TodoFilterHistory in the database.
func (_c *TodoFilterHistoryCreate) Save(ctx context.Context) (*TodoFilterHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TodoFilterHistoryCreate) SaveX(ctx context.Context) *TodoFilterHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TodoFilterHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TodoFilterHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TodoFilterHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := todofilterhistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := todofilterhistory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TodoFilterHistoryCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TodoFilterHistory.user_id"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "TodoFilterHistory.query"`)}
	}
	if v, ok := _c.mutation.Query(); ok {
		if err := todofilterhistory.QueryValidator(v); err != nil {
			return &ValidationError{Name: "query", err: fmt.Errorf(`ent: validator failed for field "TodoFilterHistory.query": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FunctionName(); ok {
		if err := todofilterhistory.FunctionNameValidator(v); err != nil {
			return &ValidationError{Name: "function_name", err: fmt.Errorf(`ent: validator failed for field "TodoFilterHistory.function_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TodoFilterHistory.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TodoFilterHistory.user"`)}
	}
	return nil
}

func (_c *TodoFilterHistoryCreate) sqlSave(ctx context.Context) (*TodoFilterHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TodoFilterHistoryCreate) createSpec() (*TodoFilterHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &TodoFilterHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(todofilterhistory.Table, sqlgraph.NewFieldSpec(todofilterhistory.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(todofilterhistory.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.FunctionName(); ok {
		_spec.SetField(todofilterhistory.FieldFunctionName, field.TypeString, value)
		_node.FunctionName = value
	}
	if value, ok := _c.mutation.Args(); ok {
		_spec.SetField(todofilterhistory.FieldArgs, field.TypeJSON, value)
		_node.Args = value
	}
	if value, ok := _c.mutation.ResultTodoIds(); ok {
		_spec.SetField(todofilterhistory.FieldResultTodoIds, field.TypeJSON, value)
		_node.ResultTodoIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(todofilterhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todofilterhistory.UserTable,
			Columns: []string{todofilterhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TodoFilterHistoryCreateBulk is the builder for creating many TodoFilterHistory entities in bulk.
type TodoFilterHistoryCreateBulk struct {
	config
	err      error
	builders []*TodoFilterHistoryCreate
}

// Save creates the TodoFilterHistory entities in the database.
func (_c *TodoFilterHistoryCreateBulk) Save(ctx context.Context) ([]*TodoFilterHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TodoFilterHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TodoFilterHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TodoFilterHistoryCreateBulk) SaveX(ctx context.Context) []*TodoFilterHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TodoFilterHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TodoFilterHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
