// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"todo-app/ent/predicate"
	"todo-app/ent/todofilterhistory"
	"todo-app/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// TodoFilterHistoryUpdate is the builder for updating TodoFilterHistory entities.
type TodoFilterHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *TodoFilterHistoryMutation
}

// Where appends a list predicates to the TodoFilterHistoryUpdate builder.
func (_u *TodoFilterHistoryUpdate) Where(ps ...predicate.TodoFilterHistory) *TodoFilterHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TodoFilterHistoryUpdate) SetUserID(v int) *TodoFilterHistoryUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TodoFilterHistoryUpdate) SetNillableUserID(v *int) *TodoFilterHistoryUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *TodoFilterHistoryUpdate) SetQuery(v string) *TodoFilterHistoryUpdate {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *TodoFilterHistoryUpdate) SetNillableQuery(v *string) *TodoFilterHistoryUpdate {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// SetFunctionName sets the "function_name" field.
func (_u *TodoFilterHistoryUpdate) SetFunctionName(v string) *TodoFilterHistoryUpdate {
	_u.mutation.SetFunctionName(v)
	return _u
}

// SetNillableFunctionName sets the "function_name" field if the given value is not nil.
func (_u *TodoFilterHistoryUpdate) SetNillableFunctionName(v *string) *TodoFilterHistoryUpdate {
	if v != nil {
		_u.SetFunctionName(*v)
	}
	return _u
}

// ClearFunctionName clears the value of the "function_name" field.
func (_u *TodoFilterHistoryUpdate) ClearFunctionName() *TodoFilterHistoryUpdate {
	_u.mutation.ClearFunctionName()
	return _u
}

// SetArgs sets the "args" field.
func (_u *TodoFilterHistoryUpdate) SetArgs(v map[string]interface{}) *TodoFilterHistoryUpdate {
	_u.mutation.SetArgs(v)
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *TodoFilterHistoryUpdate) ClearArgs() *TodoFilterHistoryUpdate {
	_u.mutation.ClearArgs()
	return _u
}

// SetResultTodoIds sets the "result_todo_ids" field.
func (_u *TodoFilterHistoryUpdate) SetResultTodoIds(v []int) *TodoFilterHistoryUpdate {
	_u.mutation.SetResultTodoIds(v)
	return _u
}

// AppendResultTodoIds appends value to the "result_todo_ids" field.
func (_u *TodoFilterHistoryUpdate) AppendResultTodoIds(v []int) *TodoFilterHistoryUpdate {
	_u.mutation.AppendResultTodoIds(v)
	return _u
}

// ClearResultTodoIds clears the value of the "result_todo_ids" field.
func (_u *TodoFilterHistoryUpdate) ClearResultTodoIds() *TodoFilterHistoryUpdate {
	_u.mutation.ClearResultTodoIds()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TodoFilterHistoryUpdate) SetUser(v *User) *TodoFilterHistoryUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TodoFilterHistoryMutation object of the builder.
func (_u *TodoFilterHistoryUpdate) Mutation() *TodoFilterHistoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TodoFilterHistoryUpdate) ClearUser() *TodoFilterHistoryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TodoFilterHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoFilterHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TodoFilterHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoFilterHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoFilterHistoryUpdate) check() error {
	if v, ok := _u.mutation.Query(); ok {
		if err := todofilterhistory.QueryValidator(v); err != nil {
			return &ValidationError{Name: "query", err: fmt.Errorf(`ent: validator failed for field "TodoFilterHistory.query": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FunctionName(); ok {
		if err := todofilterhistory.FunctionNameValidator(v); err != nil {
			return &ValidationError{Name: "function_name", err: fmt.Errorf(`ent: validator failed for field "TodoFilterHistory.function_name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TodoFilterHistory.user"`)
	}
	return nil
}

func (_u *TodoFilterHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todofilterhistory.Table, todofilterhistory.Columns, sqlgraph.NewFieldSpec(todofilterhistory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(todofilterhistory.FieldQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.FunctionName(); ok {
		_spec.SetField(todofilterhistory.FieldFunctionName, field.TypeString, value)
	}
	if _u.mutation.FunctionNameCleared() {
		_spec.ClearField(todofilterhistory.FieldFunctionName, field.TypeString)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(todofilterhistory.FieldArgs, field.TypeJSON, value)
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(todofilterhistory.FieldArgs, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultTodoIds(); ok {
		_spec.SetField(todofilterhistory.FieldResultTodoIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResultTodoIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, todofilterhistory.FieldResultTodoIds, value)
		})
	}
	if _u.mutation.ResultTodoIdsCleared() {
		_spec.ClearField(todofilterhistory.FieldResultTodoIds, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todofilterhistory.UserTable,
			Columns: []string{todofilterhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todofilterhistory.UserTable,
			Columns: []string{todofilterhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todofilterhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TodoFilterHistoryUpdateOne is the builder for updating a single TodoFilterHistory entity.
type TodoFilterHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoFilterHistoryMutation
}

// SetUserID sets the "user_id" field.
func (_u *TodoFilterHistoryUpdateOne) SetUserID(v int) *TodoFilterHistoryUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TodoFilterHistoryUpdateOne) SetNillableUserID(v *int) *TodoFilterHistoryUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetQuery sets the "query" field.
func (_u *TodoFilterHistoryUpdateOne) SetQuery(v string) *TodoFilterHistoryUpdateOne {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *TodoFilterHistoryUpdateOne) SetNillableQuery(v *string) *TodoFilterHistoryUpdateOne {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// SetFunctionName sets the "function_name" field.
func (_u *TodoFilterHistoryUpdateOne) SetFunctionName(v string) *TodoFilterHistoryUpdateOne {
	_u.mutation.SetFunctionName(v)
	return _u
}

// SetNillableFunctionName sets the "function_name" field if the given value is not nil.
func (_u *TodoFilterHistoryUpdateOne) SetNillableFunctionName(v *string) *TodoFilterHistoryUpdateOne {
	if v != nil {
		_u.SetFunctionName(*v)
	}
	return _u
}

// ClearFunctionName clears the value of the "function_name" field.
func (_u *TodoFilterHistoryUpdateOne) ClearFunctionName() *TodoFilterHistoryUpdateOne {
	_u.mutation.ClearFunctionName()
	return _u
}

// SetArgs sets the "args" field.
func (_u *TodoFilterHistoryUpdateOne) SetArgs(v map[string]interface{}) *TodoFilterHistoryUpdateOne {
	_u.mutation.SetArgs(v)
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *TodoFilterHistoryUpdateOne) ClearArgs() *TodoFilterHistoryUpdateOne {
	_u.mutation.ClearArgs()
	return _u
}

// SetResultTodoIds sets the "result_todo_ids" field.
func (_u *TodoFilterHistoryUpdateOne) SetResultTodoIds(v []int) *TodoFilterHistoryUpdateOne {
	_u.mutation.SetResultTodoIds(v)
	return _u
}

// AppendResultTodoIds appends value to the "result_todo_ids" field.
func (_u *TodoFilterHistoryUpdateOne) AppendResultTodoIds(v []int) *TodoFilterHistoryUpdateOne {
	_u.mutation.AppendResultTodoIds(v)
	return _u
}

// ClearResultTodoIds clears the value of the "result_todo_ids" field.
func (_u *TodoFilterHistoryUpdateOne) ClearResultTodoIds() *TodoFilterHistoryUpdateOne {
	_u.mutation.ClearResultTodoIds()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TodoFilterHistoryUpdateOne) SetUser(v *User) *TodoFilterHistoryUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TodoFilterHistoryMutation object of the builder.
func (_u *TodoFilterHistoryUpdateOne) Mutation() *TodoFilterHistoryMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TodoFilterHistoryUpdateOne) ClearUser() *TodoFilterHistoryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TodoFilterHistoryUpdate builder.
func (_u *TodoFilterHistoryUpdateOne) Where(ps ...predicate.TodoFilterHistory) *TodoFilterHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TodoFilterHistoryUpdateOne) Select(field string, fields ...string) *TodoFilterHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TodoFilterHistory entity.
func (_u *TodoFilterHistoryUpdateOne) Save(ctx context.Context) (*TodoFilterHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoFilterHistoryUpdateOne) SaveX(ctx context.Context) *TodoFilterHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TodoFilterHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoFilterHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoFilterHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.Query(); ok {
		if err := todofilterhistory.QueryValidator(v); err != nil {
			return &ValidationError{Name: "query", err: fmt.Errorf(`ent: validator failed for field "TodoFilterHistory.query": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FunctionName(); ok {
		if err := todofilterhistory.FunctionNameValidator(v); err != nil {
			return &ValidationError{Name: "function_name", err: fmt.Errorf(`ent: validator failed for field "TodoFilterHistory.function_name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TodoFilterHistory.user"`)
	}
	return nil
}

func (_u *TodoFilterHistoryUpdateOne) sqlSave(ctx context.Context) (_node *TodoFilterHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todofilterhistory.Table, todofilterhistory.Columns, sqlgraph.NewFieldSpec(todofilterhistory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TodoFilterHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todofilterhistory.FieldID)
		for _, f := range fields {
			if !todofilterhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todofilterhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(todofilterhistory.FieldQuery, field.TypeString, value)
	}
	if value, ok := _u.mutation.FunctionName(); ok {
		_spec.SetField(todofilterhistory.FieldFunctionName, field.TypeString, value)
	}
	if _u.mutation.FunctionNameCleared() {
		_spec.ClearField(todofilterhistory.FieldFunctionName, field.TypeString)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(todofilterhistory.FieldArgs, field.TypeJSON, value)
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(todofilterhistory.FieldArgs, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultTodoIds(); ok {
		_spec.SetField(todofilterhistory.FieldResultTodoIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResultTodoIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, todofilterhistory.FieldResultTodoIds, value)
		})
	}
	if _u.mutation.ResultTodoIdsCleared() {
		_spec.ClearField(todofilterhistory.FieldResultTodoIds, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todofilterhistory.UserTable,
			Columns: []string{todofilterhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   todofilterhistory.UserTable,
			Columns: []string{todofilterhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TodoFilterHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todofilterhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
