// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v5"
	"todo-app/ent"
	"todo-app/handlers"
	"todo-app/middleware"
	"todo-app/providers"
	"todo-app/repositories"
	"todo-app/routes"
	"todo-app/services"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	echoEcho := echo.New()
	logger := NewLogger()
	client, cleanup, err := providers.NewEntClient()
	if err != nil {
		return nil, nil, err
	}
	todoRepository := repositories.NewTodoRepository(client, logger)
	todoService := services.NewTodoService(client, logger, todoRepository)
	todoFilterHistoryRepository := repositories.NewTodoFilterHistoryRepository(client)
	todoFilterHistoryService := services.NewTodoFilterHistoryService(todoFilterHistoryRepository, logger)
	aiService := services.NewAIService(todoRepository)
	todoHandler := handlers.NewTodoHandler(logger, todoService, todoFilterHistoryService, aiService)
	todoRouter := routes.NewTodoRouter(todoHandler)
	userRepository := repositories.NewUserRepository(client)
	authService := services.NewAuthService(userRepository)
	authHandler := handlers.NewAuthHandler(logger, authService)
	authRouter := routes.NewAuthRouter(authHandler)
	authMiddleware := middleware.NewAuthMiddleware(userRepository)
	router := routes.NewRouter(todoRouter, authRouter, authMiddleware)
	app := NewApp(echoEcho, router)
	return app, func() {
		cleanup()
	}, nil
}

func InitializeTestApp(e *echo.Echo, client *ent.Client) (*App, error) {
	logger := NewLogger()
	todoRepository := repositories.NewTodoRepository(client, logger)
	todoService := services.NewTodoService(client, logger, todoRepository)
	todoFilterHistoryRepository := repositories.NewTodoFilterHistoryRepository(client)
	todoFilterHistoryService := services.NewTodoFilterHistoryService(todoFilterHistoryRepository, logger)
	aiService := services.NewAIService(todoRepository)
	todoHandler := handlers.NewTodoHandler(logger, todoService, todoFilterHistoryService, aiService)
	todoRouter := routes.NewTodoRouter(todoHandler)
	userRepository := repositories.NewUserRepository(client)
	authService := services.NewAuthService(userRepository)
	authHandler := handlers.NewAuthHandler(logger, authService)
	authRouter := routes.NewAuthRouter(authHandler)
	authMiddleware := middleware.NewAuthMiddleware(userRepository)
	router := routes.NewRouter(todoRouter, authRouter, authMiddleware)
	app := NewApp(e, router)
	return app, nil
}

// wire.go:

// todo
var todoSet = wire.NewSet(repositories.NewTodoRepository, wire.Bind(new(repositories.ITodoRepository), new(*repositories.TodoRepository)), repositories.NewTodoFilterHistoryRepository, wire.Bind(new(repositories.ITodoFilterHistoryRepository), new(*repositories.TodoFilterHistoryRepository)), services.NewTodoService, services.NewAIService, services.NewTodoFilterHistoryService, wire.Bind(new(services.ITodoFilterHistoryService), new(*services.TodoFilterHistoryService)), handlers.NewTodoHandler, routes.NewTodoRouter)

// auth
var authSet = wire.NewSet(repositories.NewUserRepository, wire.Bind(new(repositories.IUserRepository), new(*repositories.UserRepository)), services.NewAuthService, wire.Bind(new(services.IAuthService), new(*services.AuthService)), handlers.NewAuthHandler, routes.NewAuthRouter, middleware.NewAuthMiddleware)

// app
var appSet = wire.NewSet(providers.NewEntClient, routes.NewRouter, NewLogger, echo.New, NewApp)

type App struct {
	Engine *echo.Echo
	Router *routes.Router
}

func NewApp(e *echo.Echo, r *routes.Router) *App {
	return &App{Engine: e, Router: r}
}
